### ISSUE TITLE
Kanban Board Setup

### ISSUE THREAD

**Issue by yuvenalmash** [MudasirSherwani/Rails-Recipe-App#11]
[Rails-Recipe-App repository link](https://github.com/MudasirSherwani/Rails-Recipe-App)

### Group Members[ Two group members ]
- [Yuvenal Njoroge](https://github.com/yuvenalmash)
- [Mudasir Sherwani](https://github.com/MudasirSherwani)

#### Group
- Login page and registration page
- Make sure there are no N+1 queries happening
- Create a navigation menu that allows users to open all of the pages you created
- Write tests for the tasks above

#### [Yuvenal Njoroge](https://github.com/yuvenalmash)
- Food list
- Recipe details
- Write unit tests and integration tests for food list and recipe details

#### [Mudasir Sherwani](https://github.com/MudasirSherwani)
- Recipes list
- Public recipe list
- Write unit and integration tests for recipes and public recipes lists

**Comment by rloterh** [comment]
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on, but you are almost there! 
🏁  🌴 🚦 🚗 🏫  🏡   _🏃 🏃  🌴 🌴 

## Highlights 👍  
- Tasks distributed fairly!

## Required Changes ♻️
- [ ] Like in the previous boards, kindly ensure that the following columns are added to the board:
  * To Do
  * In Progress
  * In Review
  * Done

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

- [ ] [OPTIONAL]
It will be a good idea to remove the Kanban board setup card from the board, as this is not related to the main task:

**Remove the underlined:**
![image](https://user-images.githubusercontent.com/12745474/232454580-127d41d5-1b96-47f5-a7ba-72db13f6917c.png)

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Olamarx** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media4.giphy.com/media/8jqIQKr6zeh1j3UYhu/giphy.gif"/>
## Highlights
- Kanban board ✔️ 
- Equal distribution ✔️ 

## Optional suggestions
[OPTIONA] Kindly note that the link to your kanban board is what is expected you provide, not link to your repo, I would have invalidated it but because the previous reviewer forgot, I will have to go on.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by yuvenalmash** [comment]
Thanks for the review 👍🏾
